"""OG saved-area share links must land in MARKETS, carrying the token unchanged.

WHY (KK 2026-09-01, owed to Michael). Michael's CRM holds share links minted by
OG — `https://<og-host>/?area=area_XXXXXXXXXX`. His team's areas now live in
markets (the og-2026-08 import), and
scripts/og-area-import/share-id-backfill-markets.js exists to give those
imported areas their ORIGINAL OG tokens for exactly this reason
(spec-area-sharing-2026-08-20.md chunk 3). So the old links can be made to work
— by OG answering them with a redirect instead of its own app.

WHAT THIS PINS, and the two things it deliberately does NOT assume:

  1. THE REDIRECT DOES NOT DEPEND ON THE BACKFILL. OG forwards the token; it
     never asks markets whether that token resolves. If the backfill has not run
     for an area, markets answers its own honest "Shared link not found" and the
     user sees a real message on a working map. That is correct behavior, not a
     failure of this change — and it means this can ship before the backfill is
     confirmed.

  2. IT IS INERT UNTIL SOMEBODY TURNS IT ON. With MARKETS_BASE_URL unset the
     redirect does not happen and OG serves OG, exactly as today. OG prod is
     sacred and this deploys behind an env var Fable sets, so the deploy itself
     changes nothing.

The token is CASE-SENSITIVE (_SHARE_ID_ALPHABET is mixed-case) and must survive
the hop byte for byte, or the link resolves to a different area or to none.
"""
import api.main as main


MARKETS = "https://lotledger-markets-pzblpvs22a-uk.a.run.app"


def _enable(monkeypatch, base=MARKETS):
    monkeypatch.setattr(main, "_MARKETS_BASE_URL", base)


# ---------------------------------------------------------------------------
# The redirect itself
# ---------------------------------------------------------------------------
def test_og_share_link_redirects_to_markets_with_the_token_unchanged(monkeypatch):
    _enable(monkeypatch)
    assert main._markets_share_redirect_url("area_AbCdEf1234") == (
        MARKETS + "/?area=area_AbCdEf1234"
    )


def test_the_token_keeps_its_case(monkeypatch):
    """_SHARE_ID_ALPHABET is mixed-case, and markets looks the token up as an
    exact string. A redirect that lower-cased it would resolve to a different
    area, or to none — the worst possible outcome for a CRM link."""
    _enable(monkeypatch)
    url = main._markets_share_redirect_url("area_aAbBcCdDeE")
    assert url.endswith("?area=area_aAbBcCdDeE")


def test_a_trailing_slash_on_the_base_does_not_double_up(monkeypatch):
    _enable(monkeypatch, MARKETS + "/")
    assert main._markets_share_redirect_url("area_AbCdEf1234") == (
        MARKETS + "/?area=area_AbCdEf1234"
    )


# ---------------------------------------------------------------------------
# Everything that must NOT redirect
# ---------------------------------------------------------------------------
def test_no_area_param_serves_OG_as_today(monkeypatch):
    """The ordinary OG page load. This is the whole app for every user who is
    not following a share link, so it must be untouched."""
    _enable(monkeypatch)
    assert main._markets_share_redirect_url(None) is None
    assert main._markets_share_redirect_url("") is None


def test_a_malformed_token_is_NOT_redirected(monkeypatch):
    """Never bounce a user out of OG on a value we cannot recognise. A token
    that is not OG's own shape is not an OG share link."""
    _enable(monkeypatch)
    for bad in [
        "not-a-token",
        "area_short",              # too few chars
        "area_TooManyChars12",     # too many
        "area_has-a-dash1",        # outside the alphabet
        "AREA_AbCdEf1234",         # wrong prefix case
        "../../etc/passwd",
        "area_AbCdEf1234 ",        # trailing junk after a real token
    ]:
        assert main._markets_share_redirect_url(bad) is None, bad


def test_it_is_INERT_until_MARKETS_BASE_URL_is_set(monkeypatch):
    """The safety property that lets this merge and deploy without a decision.
    Unset (the default) = OG behaves exactly as it does today; Fable turns the
    reroute on by setting the env var, and can turn it off the same way."""
    monkeypatch.setattr(main, "_MARKETS_BASE_URL", "")
    assert main._markets_share_redirect_url("area_AbCdEf1234") is None
    monkeypatch.setattr(main, "_MARKETS_BASE_URL", "   ")
    assert main._markets_share_redirect_url("area_AbCdEf1234") is None


# ---------------------------------------------------------------------------
# The cross-repo contract
# ---------------------------------------------------------------------------
def test_a_REAL_OG_token_is_accepted_by_the_redirect_filter(monkeypatch):
    """Generated by OG's own minter, not hand-written. If _generate_share_id
    ever changes shape, this fails here rather than silently declining to
    redirect the links it makes."""
    _enable(monkeypatch)
    for _ in range(200):
        token = main._generate_share_id()
        assert main._markets_share_redirect_url(token) is not None, token


def test_the_token_shape_MATCHES_MARKETS_BOOT_PARSER(monkeypatch):
    """⚠️ CROSS-REPO CONTRACT, and the reason the reroute works at all.

    markets/app/map.js validates ?area= at boot with

        /^area_[A-Za-z0-9]{10}$/

    and a token failing THAT regex is dropped silently — no fetch, no toast,
    just the default map, which is precisely the blank-looking failure this
    reroute must never produce. OG's alphabet is [A-Za-z0-9] and its length is
    10, so the shapes agree today. This pins that agreement from the OG side:
    if OG's minter drifts (a longer id, a '-' added to the alphabet), the links
    would still redirect and then die quietly in markets. Fail here instead.
    """
    import re
    markets_boot_re = re.compile(r"^area_[A-Za-z0-9]{10}$")
    for _ in range(200):
        assert markets_boot_re.match(main._generate_share_id())


# ---------------------------------------------------------------------------
# THE WIRING. A correct helper nobody calls would pass every test above.
#
# index() is driven directly with a stand-in request rather than through
# TestClient: this app's startup handlers open the session DB and start the SSE
# listener, and none of that is needed to prove which response the route
# returns. Only `.query_params.get("area")` is read, so a dict is a faithful
# stand-in.
# ---------------------------------------------------------------------------
import asyncio


class _FakeRequest:
    def __init__(self, query):
        self.query_params = query


def test_the_route_ANSWERS_302_to_markets(monkeypatch):
    _enable(monkeypatch)
    resp = asyncio.run(main.index(_FakeRequest({"area": "area_AbCdEf1234"})))
    assert resp.status_code == 302, "302, never 301 — this must stay reversible"
    assert resp.headers["location"] == MARKETS + "/?area=area_AbCdEf1234"


def test_the_route_still_SERVES_THE_OG_APP_when_there_is_no_share_link(monkeypatch):
    """The regression that would matter most: every ordinary OG page load."""
    _enable(monkeypatch)
    resp = asyncio.run(main.index(_FakeRequest({})))
    assert resp.status_code == 200
    assert b"<html" in resp.body.lower()


def test_the_route_serves_OG_when_the_reroute_is_OFF(monkeypatch):
    """Deploying this with MARKETS_BASE_URL unset changes nothing at all."""
    monkeypatch.setattr(main, "_MARKETS_BASE_URL", "")
    resp = asyncio.run(main.index(_FakeRequest({"area": "area_AbCdEf1234"})))
    assert resp.status_code == 200
