# api/neighborhoods.py
# Role: read-only neighborhood overlay endpoint for the NBHD toolbar toggle.
# Connects to:
#   frontend/tx_block_groups.geojson - static POC asset generated by scripts/neighborhoods/build.py
#   frontend/map.js - consumer of the /api/neighborhoods/boundaries response
#   api/main.py - router included during app startup

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, HTTPException

from api.auth import get_current_user


router = APIRouter(prefix="/api/neighborhoods", tags=["neighborhoods"])
GEOJSON_PATH = Path(__file__).resolve().parent.parent / "frontend" / "tx_block_groups.geojson"


@router.get("/boundaries")
async def neighborhoods_boundaries(user: dict[str, Any] = Depends(get_current_user)) -> dict[str, Any]:
    if not GEOJSON_PATH.exists():
        raise HTTPException(
            status_code=503,
            detail="Neighborhood overlay data not built. Run scripts/neighborhoods/build.py.",
        )

    with GEOJSON_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)
